/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto3";

option java_package = "com.android.os.profiling.anomaly.ratelimiter.proto";
option java_multiple_files = true;

// Represents the persisted state for the ProfilingRateLimiter.
message RateLimiterStateProto {
  // Timestamps (in milliseconds since epoch) of the last N device-wide profiling requests.
  repeated int64 device_timestamps = 1;

  // Map of UID to the timestamp (in milliseconds since epoch) of its last profiling request.
  map<int32, int64> uid_timestamps = 2;

  // Map of a canonical key (UID + anomaly signature) to the timestamp (in milliseconds
  // since epoch) of its last profiling request.
  map<string, int64> signature_timestamps = 3;
}
