/*
 * Copyright (C) 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto2";

package android.os;

option java_multiple_files = true;

// LINT.IfChange(proto)
message QueuedResultsWrapper {
  message TracingSession {
    reserved 2;
    optional int32 profiling_type = 1;
    optional int32 uid = 3;
    optional string package_name = 4;
    optional string tag = 5;
    optional int64 key_most_sig_bits = 6;
    optional int64 key_least_sig_bits = 7;
    optional string file_name = 8;
    optional string redacted_file_name = 9;
    optional int32 tracing_state = 10;
    optional int32 retry_count = 11;
    optional string error_message = 12;
    optional int32 error_status = 13;
    optional int32 trigger_type = 14;
    optional int64 profiling_start_time = 15;
    optional int64 profiling_request_time = 16;
  }
  repeated TracingSession sessions = 1;
}
// LINT.ThenChange(/service/java/com/android/os/profiling/TracingSession.java:persisted_params)

