syntax = "proto2";

package android.profiling.cts;

option java_outer_classname = "ProfilingRequestClientProto";
option java_multiple_files = true;

// Request with same format as that defined internally and used for parsing.
message ClientProfilingRequest {
  message JavaHeapDump {}
  message HeapProfile {
    optional bool art = 1;
    optional uint64 sampling_interval_bytes = 2;
  }
  message StackSampling {
    optional uint32 frequency = 1;
  }
  message SystemTrace {
    optional uint32 duration_ms = 1;
  }
  message Config {
    oneof cfg_type {
      JavaHeapDump java_heap_dump = 1;
      HeapProfile heap_profile = 2;
      StackSampling stack_sampling = 3;
      SystemTrace system_trace = 4;
    }
  }
  optional Config config = 1;
}

// Request similar to that defined internally, but missing collection types.
message ClientProfilingRequestMissingTypes {
  message JavaHeapDump {}
  // Missing HeapProfile, StackSampling, and SystemTrace.
  message Config {
    oneof cfg_type {
      JavaHeapDump java_heap_dump = 1;
    }
  }
  optional Config config = 1;
}

// Request similar to that defined internally, but with collection types named
// incorrectly.
message ClientProfilingRequestMisnamedTypes {
  // Correct name: JavaHeapDump
  message JavaHeapSample {}
  // Correct name: HeapProfile
  message HeapTrace {
    optional bool art = 1;
    optional uint64 sampling_interval_bytes = 2;
  }
  // Correct name: StackSampling
  message HeapSampling {
    optional uint32 frequency = 1;
  }
  // Correct name: SystemTrace
  message Trace {
    optional uint32 duration_ms = 1;
  }
  message Configuration {
    oneof config_type {
      JavaHeapSample java_heap_sample = 1;
      HeapTrace heap_trace = 2;
      HeapSampling heap_sampling = 3;
      Trace trace = 4;
    }
  }
  optional Configuration configuration = 1;
}

// Request similar to that defined internally, but with an additional
// collection type that is non existent in the internal one.
message ClientProfilingRequestFakeType {
  message JavaHeapDump {}
  message HeapProfile {}
  message StackSampling {}
  message SystemTrace {}
  // Collection type StackDump does not exist in parsing side.
  message StackDump {}
  message Config {
    oneof cfg_type {
      JavaHeapDump java_heap_dump = 1;
      HeapProfile heap_profile = 2;
      StackSampling stack_sampling = 3;
      SystemTrace system_trace = 4;
      StackDump stack_dump = 5;
    }
  }
  optional Config config = 1;
}

// Request similar to that defined internally, but with no fields defined on
// the collection types.
message ClientProfilingRequestMissingFields {
  message JavaHeapDump {}
  message HeapProfile {}
  message StackSampling {}
  message SystemTrace {}
  message Config {
    oneof cfg_type {
      JavaHeapDump java_heap_dump = 1;
      HeapProfile heap_profile = 2;
      StackSampling stack_sampling = 3;
      SystemTrace system_trace = 4;
    }
  }
  optional Config config = 1;
}

// Request similar to that defined internally, but with additional fields set
// on JavaHeapDump that are not defined in the internal one.
message ClientProfilingRequestExtraFields {
  message JavaHeapDump {
    // All these fields do not exist on parsing side.
    optional bool java = 1;
    optional int32 heapiness = 2;
    optional bool dump = 3;
  }
  message HeapProfile {}
  message StackSampling {}
  message SystemTrace {}
  message Config {
    oneof cfg_type {
      JavaHeapDump java_heap_dump = 1;
      HeapProfile heap_profile = 2;
      StackSampling stack_sampling = 3;
      SystemTrace system_trace = 4;
    }
  }
  optional Config config = 1;
}
